INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('United States', 1, 'us');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('United Kingdom', 44, 'gb');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Afghanistan (‫افغانستان‬)', 93, 'af');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Albania (Shqipëri)', 355, 'al');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Algeria (‫الجزائر‬)', 213, 'dz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('American Samoa', 1684, 'as');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Andorra', 376, 'ad');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Angola', 244, 'ao');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Anguilla', 1264, 'ai');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Antigua and Barbuda', 1268, 'ag');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Argentina', 54, 'ar');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Armenia (Հայաստան)', 374, 'am');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Aruba', 297, 'aw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Australia', 61, 'au');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Austria (Österreich)', 43, 'at');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Azerbaijan (Azərbaycan)', 994, 'az');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bahamas', 1242, 'bs');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bahrain (‫البحرين)', 973, 'bh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bangladesh (বাংলাদেশ)', 880, 'bd');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Barbados', 1246, 'bb');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Belarus (Беларусь)', 375, 'by');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Belgium (België)', 32, 'be');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Belize', 501, 'bz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Benin (Bénin)', 229, 'bj');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bermuda', 1441, 'bm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bhutan (འབྲུག)', 975, 'bt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bolivia', 591, 'bo');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bosnia and Herzegovina (Босна и Херцеговина)', 387, 'ba');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Botswana', 267, 'bw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Brazil (Brasil)', 55, 'br');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('British Indian Ocean Territory', 246, 'io');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('British Virgin Islands', 1284, 'vg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Brunei', 673, 'bn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Bulgaria (България)', 359, 'bg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Burkina Faso', 226, 'bf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Burundi (Uburundi)', 257, 'bi');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cambodia (កម្ពុជា)', 855, 'kh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cameroon (Cameroun)', 237, 'cm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Canada', 1, 'ca');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cape Verde (Kabu Verdi)', 238, 'cv');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Caribbean Netherlands', 599, 'bq');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cayman Islands', 1345, 'ky');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Central African Republic (République centrafricaine)', 236, 'cf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Chad (Tchad)', 235, 'td');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Chile', 56, 'cl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('China (中国)', 86, 'cn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Christmas Island', 61, 'cx');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cocos (Keeling) Islands', 61, 'cc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Colombia', 57, 'co');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Comoros (‫جزر القمر‬)', 269, 'km');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 243, 'cd');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Congo (Republic) (Congo-Brazzaville)', 242, 'cg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cook Islands', 682, 'ck');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Costa Rica', 506, 'cr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Côte d’Ivoire', 225, 'ci');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Croatia (Hrvatska)', 385, 'hr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cuba', 53, 'cu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Curaçao', 599, 'cw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Cyprus (Κύπρος)', 357, 'cy');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Czech Republic (Česká republika)', 420, 'cz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('enmark (Danmark)', 45, 'dk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('jibouti', 253, 'dj');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ominica', 1767, 'dm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ominican Republic (República Dominicana)', 1, 'do');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('cuador', 593, 'ec');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('gypt (‫مصر‬)', 20, 'eg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('l Salvador', 503, 'sv');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('quatorial Guinea (Guinea Ecuatorial)', 240, 'gq');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ritrea', 291, 'er');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('stonia (Eesti)', 372, 'ee');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('thiopia', 251, 'et');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('alkland Islands (Islas Malvinas)', 500, 'fk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('aroe Islands (Føroyar)', 298, 'fo');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('iji', 679, 'fj');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('inland (Suomi)', 358, 'fi');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('rance', 33, 'fr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('rench Guiana (Guyane française)', 594, 'gf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('rench Polynesia (Polynésie française)', 689, 'pf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Gabon', 241, 'ga');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Gambia', 220, 'gm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Georgia (საქართველო)', 995, 'ge');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Germany (Deutschland)', 49, 'de');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Ghana (Gaana)', 233, 'gh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Gibraltar', 350, 'gi');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Greece (Ελλάδα)', 30, 'gr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Greenland (Kalaallit Nunaat)', 299, 'gl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Grenada', 1473, 'gd');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guadeloupe', 590, 'gp');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guam', 1671, 'gu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guatemala', 502, 'gt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guernsey', 44, 'gg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guinea (Guinée)', 224, 'gn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guinea-Bissau (Guiné Bissau)', 245, 'gw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Guyana', 592, 'gy');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Haiti', 509, 'ht');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Honduras', 504, 'hn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Hong Kong (香港)', 852, 'hk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Hungary (Magyarország)', 36, 'hu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Iceland (Ísland)', 354, 'is');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('India (भारत)', 91, 'in');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Indonesia', 62, 'id');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Iran (‫ایران‬)', 98, 'ir');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Iraq (‫العراق‬)', 964, 'iq');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Ireland', 353, 'ie');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Isle of Man', 44, 'im');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Israel (‫ישראל‬)', 972, 'il');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Italy (Italia)', 39, 'it');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Jamaica', 1876, 'jm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Japan (日本)', 81, 'jp');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Jersey', 44, 'je');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Jordan (‫الأردن‬)', 962, 'jo');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kazakhstan (Казахстан)', 7, 'kz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kenya', 254, 'ke');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kiribati', 686, 'ki');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kosovo', 383, 'xk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kuwait (‫الكويت‬)', 965, 'kw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Kyrgyzstan (Кыргызстан)', 996, 'kg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('aos (ລາວ)', 856, 'la');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('atvia (Latvija)', 371, 'lv');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ebanon (‫لبنان‬)', 961, 'lb');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('esotho', 266, 'ls');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('iberia', 231, 'lr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ibya (‫ليبيا‬)', 218, 'ly');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('iechtenstein', 423, 'li');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ithuania (Lietuva)', 370, 'lt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('uxembourg', 352, 'lu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Macau (澳門)', 853, 'mo');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Macedonia (FYROM) (Македонија)', 389, 'mk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Madagascar (Madagasikara)', 261, 'mg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Malawi', 265, 'mw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Malaysia', 60, 'my');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Maldives', 960, 'mv');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mali', 223, 'ml');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Malta', 356, 'mt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Marshall Islands', 692, 'mh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Martinique', 596, 'mq');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mauritania (‫موريتانيا‬)', 222, 'mr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mauritius (Moris)', 230, 'mu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mayotte', 262, 'yt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mexico (México)', 52, 'mx');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Micronesia', 691, 'fm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Moldova (Republica Moldova)', 373, 'md');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Monaco', 377, 'mc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mongolia (Монгол)', 976, 'mn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Montenegro (Crna Gora)', 382, 'me');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Montserrat', 1664, 'ms');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Morocco (‫المغرب‬)', 212, 'ma');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Mozambique (Moçambique)', 258, 'mz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Myanmar (Burma) (မြန်မာ)', 95, 'mm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Namibia (Namibië)', 264, 'na');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Nauru', 674, 'nr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Nepal (नेपाल)', 977, 'np');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Netherlands (Nederland)', 31, 'nl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('New Caledonia (Nouvelle-Calédonie)', 687, 'nc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('New Zealand', 64, 'nz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Nicaragua', 505, 'ni');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Niger (Nijar)', 227, 'ne');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Nigeria', 234, 'ng');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Niue', 683, 'nu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Norfolk Island', 672, 'nf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('North Korea (조선 민주주의 인민 공화국)', 850, 'kp');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Northern Mariana Islands', 1670, 'mp');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Norway (Norge)', 47, 'no');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Oman (‫عُمان‬)', 968, 'om');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('akistan (‫پاکستان‬)', 92, 'pk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('alau', 680, 'pw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('alestine (‫فلسطين‬)', 970, 'ps');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('anama (Panamá)', 507, 'pa');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('apua New Guinea', 675, 'pg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('araguay', 595, 'py');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('eru (Perú)', 51, 'pe');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('hilippines', 63, 'ph');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('oland (Polska)', 48, 'pl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ortugal', 351, 'pt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('uerto Rico', 1, 'pr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Qatar (‫قطر‬)', 974, 'qa');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('éunion (La Réunion)', 262, 're');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('omania (România)', 40, 'ro');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('ussia (Россия)', 7, 'ru');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('wanda', 250, 'rw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Barthélemy (Saint-Barthélemy)', 590, 'bl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Helena', 290, 'sh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Kitts and Nevis', 1869, 'kn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Lucia', 1758, 'lc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Martin (Saint-Martin (partie française))', 590, 'mf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)', 508, 'pm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saint Vincent and the Grenadines', 1784, 'vc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Samoa', 685, 'ws');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('San Marino', 378, 'sm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('São Tomé and Príncipe (São Tomé e Príncipe)', 239, 'st');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Saudi Arabia (‫المملكة العربية السعودية‬)', 966, 'sa');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Senegal (Sénégal)', 221, 'sn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Serbia (Србија)', 381, 'rs');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Seychelles', 248, 'sc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Sierra Leone', 232, 'sl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Singapore', 65, 'sg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Sint Maarten', 1721, 'sx');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Slovakia (Slovensko)', 421, 'sk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Slovenia (Slovenija)', 386, 'si');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Solomon Islands', 677, 'sb');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Somalia (Soomaaliya)', 252, 'so');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('South Africa', 27, 'za');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('South Korea (대한민국)', 82, 'kr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('South Sudan (‫جنوب السودان‬)', 211, 'ss');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Spain (España)', 34, 'es');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Sri Lanka (ශ්‍රී ලංකාව)', 94, 'lk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Sudan (‫السودان‬)', 249, 'sd');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Suriname', 597, 'sr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Svalbard and Jan Mayen', 47, 'sj');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Swaziland', 268, 'sz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Sweden (Sverige)', 46, 'se');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Switzerland (Schweiz)', 41, 'ch');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Syria (‫سوريا‬)', 963, 'sy');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Taiwan (台灣)', 886, 'tw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tajikistan', 992, 'tj');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tanzania', 255, 'tz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Thailand (ไทย)', 66, 'th');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Timor-Leste', 670, 'tl');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Togo', 228, 'tg');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tokelau', 690, 'tk');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tonga', 676, 'to');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Trinidad and Tobago', 1868, 'tt');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tunisia (‫تونس‬)', 216, 'tn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Turkey (Türkiye)', 90, 'tr');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Turkmenistan', 993, 'tm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Turks and Caicos Islands', 1649, 'tc');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Tuvalu', 688, 'tv');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('U.S. Virgin Islands', 1340, 'vi');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Uganda', 256, 'ug');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Ukraine (Україна)', 380, 'ua');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('United Arab Emirates (‫الإمارات العربية المتحدة‬)', 971, 'ae');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('United Kingdom', 44, 'gb');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('United States', 1, 'us');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Uruguay', 598, 'uy');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Uzbekistan (Oʻzbekiston)', 998, 'uz');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Vanuatu', 678, 'vu');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Vatican City (Città del Vaticano)', 39, 'va');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Venezuela', 58, 've');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Vietnam (Việt Nam)', 84, 'vn');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Wallis and Futuna', 681, 'wf');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Western Sahara (‫الصحراء الغربية‬)', 212, 'eh');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Yemen (‫اليمن‬)', 967, 'ye');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Zambia', 260, 'zm');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Zimbabwe', 263, 'zw');
INSERT INTO `country_dial_code` (`country_name`, `dial_code`, `country_code`) VALUE ('Åland Islands', 358, 'ax');
